### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by melekes** [tendermint/go-rpc#15]
version: fcea0cda21f64889be00a0f4b6d13266b1a76ee7

```
NOTE[03-23|16:32:23] New websocket connection                 module=rpcserver remote=127.0.0.1:61890
NOTE[03-23|16:32:23] Failed to read from connection           module=rpcserver remote=127.0.0.1:61727 err="websocket: close 1006 (abnormal closure): unexpected EOF"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1091ad2]

goroutine 36681 [running]:
time.(*Ticker).Stop(0x0)
        /usr/local/go/src/time/tick.go:46 +0x22
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server.(*wsConnection).OnStop(0xc422995680)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server/handlers.go:373 +0x6d
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common.(*BaseService).Stop(0xc422995680, 0x16f6eee)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common/service.go:117 +0x68
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server.(*wsConnection).readRoutine(0xc422995680)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server/handlers.go:444 +0xd51
created by github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server.(*wsConnection).OnStart
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server/handlers.go:346 +0x45
```

**Comment by zramsay** [comment]
Issue moved to [tendermint/tendermint #613](https://github.com/tendermint/tendermint/issues/613) via [**ZenHub**](https://www.zenhub.com/)
